### ISSUE TITLE
Übernahme der Stückzahl funktioniert nur bei ganzen Zahlen

### ISSUE THREAD

**Issue by PaulLebmann** [stefankugler/print-qrk-json#1]
Wenn die Stückzahl keine ganze Zahl ist (zB. 1,5 kg) funktioniert die Übernahme von Chromis nach QRK nicht.
Während in der json Datei die korrekte Stückzahl eingetragen ist übernimmt QRK immer nur "0".

Das Problem ist anscheindend, dass Chromis ein Komma als Dezimaltrennzeichen ausgibt und QRK einen Punkt erwartet und den Wert dann verwirft.

Ich bin mir nicht sicher ob es sinnvoller ist das als Issue bei print-qrk-json oder bei QRK direkt zu melden, daher auch hier mein Lösungsansatz:

In der bon2json.sh können die regulären Ausdrücke dahingehend angepasst werden, dass das Komma durch einen Punkt ersetzt wird.
Konkret wird die Zeile 20

`cat $pipe | sed 's/\x1D\x21\x00//g;s/\x1B\x3D\x01//g;s/\x1B\x69\x0\x0//g;s/\x1Bd0//g;s/\x1B.//g;s/\x01\x0//g' > "$qrkpath/bon.txt"`

durch

`cat $pipe | sed 's/\x1D\x21\x00//g;s/\x1B\x3D\x01//g;s/\x1B\x69\x0\x0//g;s/\x1Bd0//g;s/\x1B.//g;s/\x01\x0//g;s/count": "\([0-9]\+\),\([0-9][0-9]\?\)"/count": "\1.\2"/g' > "$qrkpath/bon.txt"`

ersetzt.

Die Regex `s/count": "\([0-9]\+\),\([0-9][0-9]\?\)"/count": "\1.\2"/g`sucht nach dem Stichwort "count nach einer Kommazahl in Anführungszeichen und ersetzt das Komma durch einen Punkt.

Für Windows kann ich leider keine Lösung anbieten. Vom fehlenden Fachwissen abgesehen habe ich kein System mit QRK und Chromis verfügbar.

btw: Vielen Dank für die großartige Schnittstelle zwischen QRK und allen Unicenta / Openbravo basierten Kassensystemen!! Es funktioniert wirklich einmalig!!

**Comment by stefankugler** [comment]
Seruvs,
sorry, ich hab mich gar nicht aktiv um dieses Issue gekümmert. Ich setze die Kombination nur in einem kleinen Bistro ein, da gibt es keine "halben Sachen" ;).

Als Alternative für Linux (und vermutlich auch Windows) habe ich den Dezimaltrenner per Velocity-Template "Printer.Ticket" ersetzt, siehe https://github.com/stefankugler/print-qrk-json/commit/955dfd5460137d70e385981439dd9dab4d3a0bd7 .

Grüße, Stefan
